// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

type Quiz struct {
	ID        string
	CreatedAt string
	UpdatedAt string
	Title     string
	UserID    string
}

type QuizQuestion struct {
	ID           string
	QuizID       string
	QuestionText string
	Choices      string
}

type User struct {
	ID        string
	CreatedAt string
	UpdatedAt string
	Email     string
	HashedPw  string
}
