// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"
)

type Quiz struct {
	ID        string
	CreatedAt string
	UpdatedAt string
	Title     string
	UserID    string
	Path      string
	DeletedAt sql.NullString
}

type QuizQuestion struct {
	ID             string
	QuizID         string
	QuestionNumber int64
	QuestionText   string
	Choice1        string
	Choice2        string
	Choice3        string
	Choice4        string
	Answer         int64
}

type RefreshToken struct {
	Token     string
	CreatedAt string
	UpdatedAt string
	UserID    string
	ExpiresAt string
	RevokedAt sql.NullString
}

type User struct {
	ID        string
	CreatedAt string
	UpdatedAt string
	Email     string
	HashedPw  string
}
