// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: users.sql

package database

import (
	"context"
)

const createUser = `-- name: CreateUser :exec
INSERT INTO users (id, created_at, updated_at, email, hashed_pw)
VALUES (
    ?,
    ?,
    ?,
    ?,
    ?
)
`

type CreateUserParams struct {
	ID        string
	CreatedAt string
	UpdatedAt string
	Email     string
	HashedPw  string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.ExecContext(ctx, createUser,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Email,
		arg.HashedPw,
	)
	return err
}

const getUser = `-- name: GetUser :one

SELECT id, created_at, updated_at, email, hashed_pw FROM users WHERE id = ?
`

func (q *Queries) GetUser(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.HashedPw,
	)
	return i, err
}
